environment:
    type: "CarRacing"
    name: "CarRacing-v2"
gamma: 0.99
lamda: 0.95
updates: 10000
epochs: 4
n_workers: 8
worker_steps: 1024
n_mini_batch: 8
value_loss_coefficient: 0.25
hidden_layer_size: 512
max_grad_norm: 0.25
continuous: True
max_action: 1.0
use_reward_scaling: True
exp_name: "CarRacing_v2"
recurrence:
    sequence_length: 8
    hidden_state_size: 256
    layer_type: lstm
    reset_hidden_state: False
learning_rate_schedule:
    initial: 2.0e-4
    final: 2.0e-4
    power: 1.0
    max_decay_steps: 300
beta_schedule:
    initial: 0.001
    final: 0.001
    power: 1.0
    max_decay_steps: 300
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 300