path: "E:/PycharmProject/torch-ngp/data/test/test.json"
fp16: True
cuda_ray: True
preload: True
lr0: 2e-2
lr1: 1e-3
num_rays: 4096
max_steps: 1024
num_steps: 512
update_extra_interval: 16
upsample_steps: 0
max_ray_batch: 4096
l1_reg_weight: 1e-5
resolution0: 128
resolution1: 300
upsample_model_steps: [2000,3000,4000,5500,7000]
color_space: "linear"
bound: 1
scale: 0.33
offset: [0,0,0]
dt_gamma: 0
min_near: 0.2
density_thresh: 10
bg_radius: -1
patch_size: 1
clip_text: ''
W: 84
H: 84
cx: 42
cy: 42
fl_x: 72.74613391789285
fl_y: 72.74613391789285
