environment:
    type: "UnityCarEnv"
    name: "TrafficCarEnv"
    use_compose: False
    exp_name: "TrafficCar7_12"
gamma: 0.99
lamda: 0.95
updates: 10000
epochs: 10
n_workers: 5
worker_steps: 2500
n_mini_batch: 8
value_loss_coefficient: 0.25
hidden_layer_size: 128
max_grad_norm: 0.25
continuous: True
max_action: 1.0
use_reward_scaling: True
exp_name: "TrafficCar7_12"
use_compose: False
use_custom_network: True
custom_network: "resnet"
recurrence:
    sequence_length: 64
    hidden_state_size: 128
    layer_type: gru
    reset_hidden_state: True
learning_rate_schedule:
    initial: 3e-4
    final: 3e-4
    power: 1.0
    max_decay_steps: 300
beta_schedule:
    initial: 0.001
    final: 0.001
    power: 1.0
    max_decay_steps: 300
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 300
