environment:
    type: "UnityCarRace"
    name: "UnityCarRace"
    use_compose: False
    exp_name: "CarRace_717"
gamma: 0.98
lamda: 0.95
updates: 10000
epochs: 10
n_workers: 1
worker_steps: 33
n_mini_batch: 8
value_loss_coefficient: 0.25
hidden_layer_size: 512
max_grad_norm: 0.25
continuous: True
max_action: 1.0
use_reward_scaling: True
exp_name: "CarRace_717"
use_compose: False
use_custom_network: False
custom_network: "resnet"
recurrence:
    sequence_length: 32
    hidden_state_size: 128
    layer_type: gru
    reset_hidden_state: True
learning_rate_schedule:
    initial: 1e-4
    final: 1e-4
    power: 1.0
    max_decay_steps: 300
beta_schedule:
    initial: 0.001
    final: 0.001
    power: 1.0
    max_decay_steps: 300
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 300
